### ISSUE TITLE
no longer being serviced error

### ISSUE THREAD

**Issue by Delgathar** [Caraxi/Honorific#1]
![image](https://user-images.githubusercontent.com/9401098/234436744-c12f3446-7b6f-40cb-b0c7-81604c855355.png)

So I'm getting this error.  Is the location moving or is this great plugin being discontinued already?

**Comment by XiKav** [comment]
well having the same question.

**Comment by Lexden12** [comment]
Honorific has been moved to plugin testing builds in Dalamud, so the repo is being retired.
Opt in to plugin testing builds and you'll be able to find it again:
![image](https://user-images.githubusercontent.com/24421791/235061505-0db79e81-30f8-432b-86cc-11c27a37e417.png)

**Comment by wackydude1234** [comment]
> Honorific has been moved to plugin testing builds in Dalamud, so the repo is being retired. Opt in to plugin testing builds and you'll be able to find it again: ![image](https://user-images.githubusercontent.com/24421791/235061505-0db79e81-30f8-432b-86cc-11c27a37e417.png)

Doing this says "Honorific is now on the main repo [DO NOT INSTALL THIS ONE]
