### ISSUE TITLE
Suggestion: Make only custom titles visible

### ISSUE THREAD

**Issue by iv230** [Caraxi/Honorific#10]
To reduce the amount of information displayed on my screen I disabled titeles visibility. But I'm interested to see my freinds custom titeles through Mare Synchronos. I so suggest an option to make all vanilla titles not visible above other players head (or replace them by empty string?) and display only the ones that are custom!

**Comment by Caraxi** [comment]
This has been added as of 1.4.1
0e8956ff2e34f11c4ca3f46e9a1fc3e56598900e
