### ISSUE TITLE
Giant black screen?

### ISSUE THREAD

**Issue by Sylphrena-Sedai** [Caraxi/Honorific#11]
When I open Honorific it is just a giant menu that covers all 3 of my monitors so they are all just black. I can't do a thing with it other than minimise and maximise it. I've uninstalled and reinstalled it multiple times. Cleared out the repository too. Not sure what else to do? 

<img width="3384" alt="ffxiv_dx11_dBdj9THpxy" src="https://github.com/Caraxi/Honorific/assets/150967039/a8783914-7a9f-4eba-bda4-759817220973">

**Comment by Caraxi** [comment]
You broke your UI somehow

[![image](https://github.com/Caraxi/Honorific/assets/11886749/1ebf9318-01f7-4944-8255-0369bdd0fead)](https://goatcorp.github.io/faq/dalamud_troubleshooting#q-how-do-i-reset-dalamudplugin-window-locations)
