### ISSUE TITLE
[Suggestion/Request] Ability to set titles via command

### ISSUE THREAD

**Issue by PrincessRTFM** [Caraxi/Honorific#6]
I like to periodically shuffle my active title from a pool of ones I particularly like, usually with a theme. For instance, I have one pool for DoW jobs and another for DoM jobs. Right now, I can use QoLBar's random categories or a WoLua script to randomise my title from the _vanilla_ pool by using the `/title set <title text>` command, but Honorific has no such ability. I have to open the config window to pick a different title, outside of using the class/job/role condition mechanism.

I don't know how feasible any of these ideas are, but hopefully at least something will be viable without too much work:
- something like `/honorific set <index>` to use a particular title from the current character config, and `/honorific change <title text>` to change the text of the currently active title entry
- something like `/honorific override [<title text>]` or `/honorific force [<title text>]` to apply a particular title override or clear the override if nothing is provided
- something like `/honorific default <title text>` to change the "default title" entry in the current character config, which would then allow someone to only use the default title slot and just change it periodically (probably easiest, I'd guess?)

A simpler-to-use and more generalised solution (but also one that I imagine would take more effort to implement) would be to allow setting multiple titles for various conditions and then pick one at random when that condition becomes met. For instance, with four titles with the condition of "role = DPS", when changing jobs to a DPS role, one title would be chosen at random. The complication here would be compounding of conditions: if there are titles with the condition "role = DPS" and titles with the condition "role = magic DPS" and the player switches to, eg, RDM, should only the more specific condition be used, or should both pools be considered?

**Comment by Caraxi** [comment]
I've added support for commands in version `1.3.1.0`

Examples:
`/honorific force set New Title` - Set title to suffix of "New Title" with no colour or glow.
`/honorific force set New Title | prefix` - Set title to prefix of "New Title" with no colour or glow.
`/honorific force set New Title | #ff0000` - Set title to suffix of "New Title" in red with no glow.
`/honorific force set New Title | prefix | #ff0000 | #00ffff` - Set title to prefix of "New Title" in red with an aqua glow.
`/honorific force clear` - Clears title set by command. 


Randomly picking might come one day but likely far off for now
