### ISSUE TITLE
Appears to be causing a crash when entering aesthetician

### ISSUE THREAD

**Issue by Gazzoo-byte** [Caraxi/Honorific#8]
[dalamud_appcrash_20231006_134222_615_11208.log](https://github.com/Caraxi/Honorific/files/12831276/dalamud_appcrash_20231006_134222_615_11208.log)

Log attached, could be coincidence but turning off Honorific makes it not crash, if any further information is needed I'll do my best

**Comment by Caraxi** [comment]
Its likely a remnant of some issues it was having with 1.2.2.0
Try updating to the latest version, please report if the issue still occurs
