### ISSUE TITLE
honorific appears to be preventing me from scrolling down in the keybinds menu

### ISSUE THREAD

**Issue by Arveene** [Caraxi/Honorific#9]
it's possible i didn't do enough to isolate the issue, but honorific appears to be resetting my scrolling on the keybinds menu. these are the steps i took to isolate it to honorific:

1. Start game using regular launcher to see if it was happening there as well, it was not.
2. Disable all plugins and then re-enable one at a time and check.
3. When I got to Honorific and checked it started to happen again.

I toggled it on and off multiple times, with honorific off I was able to scroll down in my keybinds menu. When it was on, it kept resetting back to the top. 

I have a video of it as well that I can send you privately.

**Comment by Caraxi** [comment]
This was fixed in 1.2.2.2
Were you on the latest version?
